services:
  backend:
    build:
      context: ./backend
    environment:
      - GENIE_ENV=prod
    ports:
      - "8000:8000"
    networks:
      - ebola
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    networks:
      - ebola
    depends_on:
      - backend
    restart: unless-stopped

networks:
  ebola:
    external: true
